### ISSUE TITLE
[BUG] RuntimeError: NG0203: inputFunction() can only be used within an injection context

### ISSUE THREAD

**Issue by esmeetewinkel** [IDEMSInternational/open-app-builder#2906]
**Describe the bug**
ESM app home screen shows blank and error in console.

``error-handler.service.ts:69 ERROR RuntimeError: NG0203: inputFunction() can only be used within an injection context such as a constructor, a factory function, a field initializer, or a function used with `runInInjectionContext`. Find more at https://angular.io/errors/NG0203``

**App version**
Not working on 0.18.2+ (current `master`, e.g. commit 585188f)
Still working on commit 99d7b22
So I'm guessing the culprit is PR #2900 

**Deployment Sheet(s)**
[Early School Math](https://github.com/IDEMSInternational/early-school-math-app-content) deployment home screen

**Screenshots and videos**

![Image](https://github.com/user-attachments/assets/1b2020a9-84bc-42ec-90f6-c96e24432548)
